/**
 * DESIGN.md renderer.
 *
 * Pure function: takes a FullStyle, returns markdown. Idempotent — same
 * input produces the same output (timestamp uses captured/extracted_at, not
 * Date.now), so re-running this on the same style produces a stable file.
 *
 * Author: Nate Davidovich (Lorecraft LLC)
 */
import type { DesignSystemColor, FullStyle } from "./types.js";

const REFERO_DETAIL_BASE = "https://styles.refero.design/styles";

function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function yamlEscape(value: string): string {
  // Quote whenever the value contains characters YAML treats specially.
  if (/^[\w\-./: ]+$/.test(value) && !value.startsWith(" ") && !value.endsWith(" ")) {
    if (/^(true|false|null|yes|no|on|off)$/i.test(value)) return `"${value}"`;
    if (/^-?\d+(\.\d+)?$/.test(value)) return `"${value}"`;
    return value;
  }
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function yamlList(values: string[]): string {
  if (values.length === 0) return "[]";
  return `[${values.map((v) => yamlEscape(v)).join(", ")}]`;
}

function isoDay(input?: string | number): string {
  // Refero list returns "YYYY-MM-DD HH:MM:SS"; detail returns ISO 8601.
  // Normalise both to YYYY-MM-DD.
  if (typeof input === "string" && input.length >= 10) {
    // Try the cheap path first — first 10 chars look like a date.
    const head = input.slice(0, 10);
    if (/^\d{4}-\d{2}-\d{2}$/.test(head)) return head;
  }
  const d = input ? new Date(input) : new Date();
  if (Number.isNaN(d.getTime())) return new Date().toISOString().slice(0, 10);
  return d.toISOString().slice(0, 10);
}

function colorRow(c: DesignSystemColor): string {
  return `| \`${escapePipe(c.hex)}\` | ${escapePipe(c.name ?? "")} | ${escapePipe(c.role ?? "")} | ${escapePipe(c.group ?? "")} |`;
}

/** Render a clean DESIGN.md from a FullStyle. */
export function renderDesignMd(full: FullStyle): string {
  const ds = full.fullResult.designSystem;
  const detailUrl = `${REFERO_DETAIL_BASE}/${full.id}`;
  const extractedAt = isoDay(full.previewVideoCapturedAt ?? full.createdAt);

  // ---- Frontmatter ----
  const fmLines: string[] = [
    "---",
    `source_url: ${yamlEscape(full.url)}`,
    `site_name: ${yamlEscape(full.siteName)}`,
    `extracted_at: ${yamlEscape(extractedAt)}`,
    `theme: ${yamlEscape(ds.theme ?? full.colorScheme)}`,
  ];
  if (full.industry) fmLines.push(`industry: ${yamlEscape(full.industry)}`);
  fmLines.push(`tags: ${yamlList(ds.tags ?? [])}`);
  fmLines.push("---", "");

  // ---- Heading + north star ----
  const lines: string[] = [
    ...fmLines,
    `# ${full.siteName}`,
    "",
  ];
  if (full.northStar && full.northStar.trim()) {
    for (const ln of full.northStar.trim().split(/\r?\n/)) {
      lines.push(`> ${ln}`);
    }
    lines.push("");
  }

  // ---- Colors ----
  const colors = ds.colors ?? [];
  if (colors.length > 0) {
    lines.push(
      "## Colors",
      "",
      "| Hex | Name | Role | Group |",
      "| --- | --- | --- | --- |",
      ...colors.map(colorRow),
      "",
    );
  }

  // ---- Fonts ----
  const fonts = ds.fonts ?? full.fonts ?? [];
  if (fonts.length > 0) {
    lines.push(
      "## Fonts",
      "",
      ...fonts.map((f) => `- ${f}`),
      "",
    );
  }

  // ---- Do ----
  if ((ds.dos ?? []).length > 0) {
    lines.push(
      "## Do",
      "",
      ...ds.dos.map((d) => `- ${d}`),
      "",
    );
  }

  // ---- Don't ----
  if ((ds.donts ?? []).length > 0) {
    lines.push(
      "## Don't",
      "",
      ...ds.donts.map((d) => `- ${d}`),
      "",
    );
  }

  // ---- Tags ----
  if ((ds.tags ?? []).length > 0) {
    lines.push(
      "## Tags",
      "",
      ds.tags.map((t) => `\`${t}\``).join(" · "),
      "",
    );
  }

  // ---- Footer ----
  lines.push(
    "---",
    "",
    `Generated by refero-mcp from ${detailUrl} on ${extractedAt}`,
    "",
  );

  return lines.join("\n");
}
